### ISSUE TITLE
Full width change for larger iOS devices.

### ISSUE THREAD

**Issue by ajrahim** [JayGajjar/JGTransitionCollectionView#3]
I noticed that it wasn't going full width when looking at some of the larger devices. Possible solution may be to change **self.collectionView!.frame.size.width/2** to **UIScreen.mainScreen().bounds.width/2** in the **JGTransitionLayout.swift**.

If anyone knows a better solution please let me know :)

**Comment by JayGajjar** [comment]
Code is updated to support full width of the screen. It will work on large screen devices even on ipads.
